In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os
import keyboard

In [2]:
import run_parallel

In [3]:
# Running in parallel
run_parallel.main()

ep
THIS IS ORIGINAL FOLDER PATH /Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code
/Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/focus
['test.tiff', 'test2.tiff', '.gitkeep', 'test2 còpia.tiff']
ROI PATH /Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/focus/test2 còpia.tiff
Select the ROI. Press right button if you want to delete. The last 2 ROIs will be used as background. Press 'q' when you have finished. 
ROIs:
 [[2944 1840  480]
 [ 636 2044  480]
 [1784 3016  480]
 [3680 2936  480]]
OBSERVED FOLDER /Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/images/20210828
Press "s" or ctrl+c to exit and save the results


Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Applications/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Applications/anaconda3/lib/python3.7/site-packages/keyboard/__init__.py", line 294, in listen
    _os_keyboard.listen(self.direct_callback)
  File "/Applications/anaconda3/lib/python3.7/site-packages/keyboard/_darwinkeyboard.py", line 430, in listen
    raise OSError("Error 13 - Must be run as administrator")
OSError: Error 13 - Must be run as administrator



filename /Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/images/20210828/Brightfield còpia 20.png
num events 1
imgs (1, 3648, 5472)
filename /Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/images/20210828/Brightfield còpia 21.png
num events 2
imgs (2, 3648, 5472)
filename /Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/images/20210828/Brightfield còpia 22.png
num events 3
imgs (3, 3648, 5472)
filename /Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/images/20210828/Brightfield còpia 23.png
num events 4
imgs (4, 3648, 5472)
filename /Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/images/20210828/Brightfield còpia 24.png
num events 5

 Computing temporal median filter with kernel size  5 ...
Averaged images shape:  (1, 3648, 5472)
Correcting background illumination intensi

/Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/processing/processing_functions.py:153: RuntimeWarning: invalid value encountered in true_divide
  img_corrected_norm = np.array((img_corrected-img_corrected.min()) / (img_corrected.max()-img_corrected.min()) * 255, dtype=np.uint8)


Corrected images shape:  (1, 3648, 5472)
Inverting images...
Inverted images shape:  (1, 3648, 5472)
Binarizing images...
Thresholded images shape:  (1, 3648, 5472)
Percentage of pixels detected in each ROI (0-1) [0.0, 0.0, 0.0, 0.0]
Percentage of pixels corresponding to Background (0-1) 0.0
Percentage of pixels corresponding to Foreground (0-1) 0.0
Percentage of pixels corresponding to Signal 0.0
[[], [0.0, 0.0, 0.0]]
filename /Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/images/20210828/Brightfield còpia 25.png
num events 1
imgs (1, 3648, 5472)
filename /Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/images/20210828/Darkfield còpia 7.png
num events 2
imgs (2, 3648, 5472)
filename /Users/janet/EnginyeriaBiomèdica/MSc LIFE SCIENCES ENGINEERING/SensUs/Code/SensUs_2021_Code/images/20210828/Brightfield còpia 26.png
num events 3
imgs (3, 3648, 5472)
filename /Users/janet/EnginyeriaBiomèdica/MSc LIFE S

SystemExit: 

/Applications/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


<Figure size 432x288 with 0 Axes>

In [ ]:
# Running pump TODO

In [ ]:
# Loading results
result_df = pd.read_csv('./images/20210828/result.csv')
result_df['Signal'].plot()

In [ ]:
print(keyboard.is_pressed('ctrl'))

In [ ]:
while True:  # making a loop
    try:  # used try so that if user pressed other than the given key error will not be shown
        if keyboard.is_pressed('q'):  # if key 'q' is pressed 
            print('You Pressed A Key!')
            break  # finishing the loop
    except:
        break  # if user pressed a key other than the given key the loop will break

In [ ]:
# todo: median filter